{
  "gilded": 0,
  "upvotes": 1,
  "saved": false,
  "unread": null,
  "approvedBy": null,
  "body": " Confirmed",
  "subreddit": "Pen_Swap",
  "liked": null,
  "authorFlairCssClass": null,
  "archived": false,
  "score": 1,
  "approved": false,
  "subredditNamePrefixed": "r/Pen_Swap",
  "bodyHtml": "&lt;div class=\"md\"&gt;&lt;p&gt;Confirmed&lt;/p&gt;\n&lt;/div&gt;",
  "id": "fvvj6zv",
  "locked": false,
  "edited": false,
  "created": 1.593051364E9,
  "author": "socal-chicana",
  "subredditId": "t5_2tyn2",
  "downvotes": 0,
  "parentId": "t1_fvveqa6",
  "linkTitle": "June 2020 Confirmed Trade Thread",
  "authorFlairText": "Trades: 2",
  "linkId": "t3_hc4tdw",
  "stickied": false,
  "removed": false,
  "replies": "",
  "numReports": 0,
  "linkPermalink": "https://www.reddit.com/r/Pen_Swap/comments/hc4tdw/june_2020_confirmed_trade_thread/",
  "bannedBy": null,
  "editedAt": null,
  "name": "t1_fvvj6zv",
  "permalink": "/r/Pen_Swap/comments/hc4tdw/june_2020_confirmed_trade_thread/fvvj6zv/",
  "linkAuthor": "FPPenSwapBot",
  "createdUtc": 1.593022564E9
}